### PR TITLE
Get practice email

### PR DESCRIPTION
**Pull request by teneightfive**
This gets the practice email address from the environment variables
and uses that as the email send method.

It checks that the practice is in the accepted list and then converts
the key to a constant format so that it can get the value of the
email for that practice.

The email addresses will be stored as environment variables as the
emails provided my not be for public use.

### CODE REVIEW

**Comment by teneightfive** [comment]
Need to find a way to mock environment variables for the get email function.

**Comment by r4vi** [comment]
@teneightfive process.env is mutable you can just copy it, change and restore after test

**Comment by teneightfive** [comment]
Good shout. Will sort tomorrow.

**Comment by teneightfive** [comment]
@r4vi have made updates to #53 as no longer have write access. Might want to move those changes to this branch or merge that PR and close this one.

**Pull request merged**
