### PR TITLE
:boom: Initial deployment config

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by teneightfive** [comment]
@adamgraves-choices do we need to add anything to the README as to how this is run?

**Comment by adamgraves-choices** [comment]
@teneightfive Yeah I will do, currently it relies on https://github.com/nhsuk/ci-deployment/, not sure how much duplication will be need in this repos README.

**Comment by teneightfive** [comment]
@adamgraves-choices maybe even a link to that README. But it's worth making a not how to run that and how it's being used

**Comment by adamgraves-choices** [comment]
@teneightfive It'll be done before the WIP label is removed. 👍

**Pull request merged**
