### PR TITLE
Use first specific version of nhsuk-frontend

### PR DESCRIPTION
**Pull request by tyom**
Start using tagged version 0.1.0.

### CODE REVIEW

**Comment by r4vi** [comment]
@tyom I'm getting the same failure as the CI locally

**Comment by r4vi** [comment]
@tyom it works again if I change `devtool: "cheap-source-map"` in webpack config

```cheap-source-map```

```
Hash: d4d7296fb4d11530b9c1
Version: webpack 2.2.1
Time: 1422ms
                                  Asset       Size  Chunks             Chunk Names
   2c533d8e14f0e9ffedf6f67bcc797d19.png  648 bytes          [emitted]  
   63106a89fb653ac0e931b0f14ead7398.png    1.19 kB          [emitted]  
   02f0ae015bbb35b18e520a43eaef86b5.png    2.12 kB          [emitted]  
   e32db382aafdc5be6bed3bb8aebc5651.png    4.11 kB          [emitted]  
    main.bundle.d4d7296fb4d11530b9c1.js  940 bytes       0  [emitted]  main
          main.d4d7296fb4d11530b9c1.css    15.9 kB       0  [emitted]  main
main.bundle.d4d7296fb4d11530b9c1.js.map    1.13 kB       0  [emitted]  main
      main.d4d7296fb4d11530b9c1.css.map   95 bytes       0  [emitted]  main
   [0] ./src/client/js/index.js 264 bytes {0} [built]
   [1] ./src/client/styles/index.js 192 bytes {0} [built]
   [2] ./src/client/js/lib/title.js 129 bytes {0} [built]
   [3] ./src/client/styles/base.scss 41 bytes {0} [built]
   [4] multi ./src/client/js ./src/client/styles 40 bytes {0} [built]
   [5] ./~/css-loader?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true,"importOnce":{"index":true,"css":true},"includePaths":["/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules"]}!./src/client/styles/base.scss 80.6 kB [built]
   [6] ./~/css-loader/lib/css-base.js 1.51 kB [built]
   [7] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour.png 82 bytes [built]
   [8] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour@2x.png 82 bytes [built]
   [9] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse.png 82 bytes [built]
  [10] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse@2x.png 82 bytes [built]
  [11] ./~/style-loader/addStyles.js 7.15 kB [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour.png 82 bytes {0} [built]
       [2] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour@2x.png 82 bytes {0} [built]
       [3] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse.png 82 bytes {0} [built]
       [4] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse@2x.png 82 bytes {0} [built]
       [5] ./~/css-loader?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true,"importOnce":{"index":true,"css":true},"includePaths":["/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules"]}!./src/client/styles/base.scss 80.6 kB {0} [built]
```


vs
```source-map```


```
Hash: d4d7296fb4d11530b9c1
Version: webpack 2.2.1
Time: 1422ms
                                  Asset       Size  Chunks             Chunk Names
   2c533d8e14f0e9ffedf6f67bcc797d19.png  648 bytes          [emitted]  
   63106a89fb653ac0e931b0f14ead7398.png    1.19 kB          [emitted]  
   02f0ae015bbb35b18e520a43eaef86b5.png    2.12 kB          [emitted]  
   e32db382aafdc5be6bed3bb8aebc5651.png    4.11 kB          [emitted]  
    main.bundle.d4d7296fb4d11530b9c1.js  940 bytes       0  [emitted]  main
          main.d4d7296fb4d11530b9c1.css    15.9 kB       0  [emitted]  main
main.bundle.d4d7296fb4d11530b9c1.js.map    1.13 kB       0  [emitted]  main
      main.d4d7296fb4d11530b9c1.css.map   95 bytes       0  [emitted]  main
   [0] ./src/client/js/index.js 264 bytes {0} [built]
   [1] ./src/client/styles/index.js 192 bytes {0} [built]
   [2] ./src/client/js/lib/title.js 129 bytes {0} [built]
   [3] ./src/client/styles/base.scss 41 bytes {0} [built]
   [4] multi ./src/client/js ./src/client/styles 40 bytes {0} [built]
   [5] ./~/css-loader?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true,"importOnce":{"index":true,"css":true},"includePaths":["/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules"]}!./src/client/styles/base.scss 80.6 kB [built]
   [6] ./~/css-loader/lib/css-base.js 1.51 kB [built]
   [7] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour.png 82 bytes [built]
   [8] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour@2x.png 82 bytes [built]
   [9] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse.png 82 bytes [built]
  [10] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse@2x.png 82 bytes [built]
  [11] ./~/style-loader/addStyles.js 7.15 kB [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour.png 82 bytes {0} [built]
       [2] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour@2x.png 82 bytes {0} [built]
       [3] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse.png 82 bytes {0} [built]
       [4] ../nhsuk-frontend/dist/assets/images/logotype-nhs-colour__reverse@2x.png 82 bytes {0} [built]
       [5] ./~/css-loader?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true,"importOnce":{"index":true,"css":true},"includePaths":["/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules"]}!./src/client/styles/base.scss 80.6 kB {0} [built]
ravi@ ~/code/nhs/register-with-a-gp-beta-web (bump-nhsuk-frontend)*$ ./node_modules/.bin/webpack -p --config src/client/webpack.config.babel.js 
/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-map-generator.js:277
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":1,"column":10265},"source":"webpack:///node_modules/nhsuk-frontend/dist/scss/environment/tools/_mixins.scss","original":{"line":22,"column":-2},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-node.js:345:13
    at SourceNode_walk [as walk] (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-node.js:224:9)
    at SourceNode_walk [as walk] (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_walk [as walk] (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/source-map/lib/source-node.js:336:8)
    at ConcatSource.proto.sourceAndMap (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:32)
    at Compilation.<anonymous> (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins1 (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack/lib/Compilation.js:630:11)
    at next (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:5)
    at Compilation.applyPluginsAsyncSeries (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack/lib/Compilation.js:626:10)
    at next (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/extract-text-webpack-plugin/index.js:329:4)
    at Compilation.applyPluginsAsyncSeries (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/webpack/lib/Compilation.js:622:9)
    at next (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/tapable/lib/Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/extract-text-webpack-plugin/index.js:305:5)
    at /home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/async/dist/async.js:936:13)
    at /home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/async/dist/async.js:840:16
    at /home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/extract-text-webpack-plugin/index.js:289:6
    at /home/ravi/code/nhs/register-with-a-gp-beta-web/node_modules/async/dist/async.js:356:16
```

**Comment by tyom** [comment]
@r4vi Hmm.. Looks like an issue with `webpack -p` again. I'll investigate.

**Comment by r4vi** [comment]
@tyom 'cheap-module-source-map' seems to work and link to the original .scss so shall we just change to that?

**Comment by tyom** [comment]
'cheap-module-source-map' seems to work and link to the original .scss so shall we just change to that?

Hang on @ravi. I'd like to better understand what went wrong.

**Comment by r4vi** [comment]
@tyom yeah just letting you know it's an option if you can't figure it out/don't want to spend hours on it

**Comment by tyom** [comment]
@r4vi The other option could be to only add source maps on the server.

**Comment by r4vi** [comment]
I like the idea of having source maps available on production

**Comment by tyom** [comment]
`cheap-source-map` is less desirable as it produces wrong file names and lines.

**Comment by tyom** [comment]
I've updated source maps as suggested in [blog post about source maps](http://cheng.logdown.com/posts/2016/03/25/679045).

**Pull request merged**
